### PR TITLE
Don't send JWT for "guest" role

### PR DESCRIPTION
**Pull request by aleixq**
As noted in #19 , we don't want the jwt for all the roles.

### CODE REVIEW

**Comment by SergioComeron** [comment]
Hi @aleixq ,
I think it is not a good solution for the problem, since this would cause in some configurations that a user that does not have the moderation capacity could not enter a session.

**Comment by aleixq** [comment]
Hola sergio,

Well, I think that it matters how jitsi is configured. In my case jitsi is configured in a way that: 
The users with token can create and moderate rooms, one room is created, guest users with no token are accepted.(as a background look at https://community.jitsi.org/t/rocket-jitsi-how-setup-authenticated-and-anonymous-access-together/21047/10 ) Configured in such way there are no problems with this PR... 


But often is configured in a way that only users with token are accepted. But I think that this way leads to "everybody is moderator". And that is not acceptable in the 99% of cases of a classroom scopes,  as guest can kick out teacher...  

Maybe an option to be strict or not about this could help.

**Comment by SergioComeron** [comment]
Yes, I am sure that the issue of the guests is a problem and it must be solved. But for example your solution causes that students (who do not have moderation permission) cannot enter a session, since no token is provided (with or without moderation).
In your case, do students also have moderation permission?

**Comment by aleixq** [comment]
Yes, they can enter once upon a moderator is there.

**Comment by bozicm** [comment]
> Yes, they can enter once upon a moderator is there.

That is the correct behaviour that teachers expect. The latest Jitsi updates support this kind of lobby room.

**Pull request closed without merging**
