### PR TITLE
added support for boost child themes

### PR DESCRIPTION
**Pull request by samuelcalegari**

### CODE REVIEW

**Comment by SergioComeron** [comment]
Hi @samuelcalegari 
sorry for the delay. 
I remember that with older versions of 3.6 there were many problems with the themes. Do you think that with this we would solve all those problems?

**Comment by SergioComeron** [comment]
Thanks @samuelcalegari 
will be in the next version

**Comment by SergioComeron** [comment]
Thanks

**Comment by samuelcalegari** [comment]
yes i use moodle 3.5
thanks for merging ;)

Le jeu. 25 juin 2020 à 10:48, Sergio Comerón <notifications@github.com> a
écrit :

**Pull request merged**
